version: '3.8'

services:
  frontend:
    container_name: chat-frontend
    image: chat-frontend-app

    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=https://chatapp-1-8ca1.onrender.com/
    ports:
      - "5173:80"
    restart: always