version: '3.8'

services:
  backend:
    container_name: chat-backend-app
    build:
      context: ./backend
      dockerfile: Dockerfile
    
    ports:
      - "${PORT}:${PORT}" # Lấy port từ file .env luôn cho đồng bộ
      
    environment:
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - NODE_ENV=production 
    
    restart: always